### ISSUE TITLE
Add T - 36h counter

### ISSUE THREAD

**Issue by rgascons** [hackupc/old-v2-hackupc-landing#100]

**Comment by casassg** [comment]
Do you mean update it to show 36h now?

**Comment by casassg** [comment]
@rgascons could you elaborate please?

**Comment by rgascons** [comment]
No :( I meant a backwards counter from 36h to 0h (hackathon starts)

**Comment by AsLogd** [comment]
@rgascons this was what you meant right? (Check live now)
