### ISSUE TITLE
Can't scroll schedule in android webview

### ISSUE THREAD

**Issue by AsLogd** [hackupc/old-v2-hackupc-landing#106]
For example, opening from facebook

**Comment by ofpau** [comment]
It works fine for me. Anyone else with this problem?

**Comment by casassg** [comment]
It works fine for me on WebView created on Slack in a Android M. Please specify where is the problem

**Comment by AsLogd** [comment]
It happens in chromium mobile 51 (2009) which I assume it's like the default browser for me. No problems in chrome for mobile
