### ISSUE TITLE
Add MLH Hardware live availability

### ISSUE THREAD

**Issue by casassg** [hackupc/old-v2-hackupc-landing#113]
There's an API endpoint for live availability of items from MLH Hardware Lab:

https://hardware.mlh.io/events/hackupc-winter.json

**Comment by casassg** [comment]
Is giving me a CORS problem. If someone else wants to see, I did the code on branch mlh_hw_live

**Comment by AsLogd** [comment]
I'll take a look later

**Comment by casassg** [comment]
Okay, checked again, still can't make it work. CORS is not activated on the server. (cc  @bih )
