### ISSUE TITLE
Live: Can't use Ctrl+F

### ISSUE THREAD

**Issue by ofpau** [hackupc/old-v2-hackupc-landing#114]
The key to activate fullscreen is **f**. That makes it difficult to use Ctrl+F to find something in the schedule, which I think many people would use to look up the time of a particular event (for example).

I suggest changing the fullscreen key to anything else. Code is [here](https://github.com/hackupc/frontend/blob/6781a99550f36beaf31d58c79b095a050e3c8175/src/scripts/live.js#L452).

**Comment by AsLogd** [comment]
how about Ctrl+alt+f? @ofpau

**Comment by ofpau** [comment]
That sounds good. So it's possible to detect those three keys pressed at once? Could you do it @AsLogd ?

If it's easier we can just choose another (single) letter, like **p** as in "**p**resentation mode".

**Comment by AsLogd** [comment]
Allright. p it is. I'll make a batch of short fixes right now
