### ISSUE TITLE
Countdown to hackathon start is misleading people

### ISSUE THREAD

**Issue by AsLogd** [hackupc/old-v2-hackupc-landing#118]
Should we remove it? make a distinction?

**Comment by casassg** [comment]
I would take it away. It's not that important.

**Comment by AsLogd** [comment]
I agree. Something to add @rgascons @ofpau ?

**Comment by ofpau** [comment]
Yeah it's a bit confusing. Let's remove it for now and we can think of a better way to do it next time.

**Comment by AsLogd** [comment]
@ofpau can you do it?
