### ISSUE TITLE
Facebook thumbnail broken on /live 

### ISSUE THREAD

**Issue by mllobet** [hackupc/old-v2-hackupc-landing#12]
Facebook shows 404 when posting hackupc.com/live

<img width="506" alt="screenshot 2016-02-18 15 15 29" src="https://cloud.githubusercontent.com/assets/868837/13145682/a11ae184-d652-11e5-9061-a7f625fe6218.png">

**Comment by dasilvacontin** [comment]
@mllobet feel free to add meta tags in `live.html` and send a PR.

After merge, `master` is automatically deployed now, and you can just invalidate FB cache using https://developers.facebook.com/tools/debug/.
