### ISSUE TITLE
Add Bloomberg logo to frontend

### ISSUE THREAD

**Issue by AlbertSuarez** [hackupc/old-v2-hackupc-landing#159]
Tier: Kilo
https://drive.google.com/open?id=0B2Kw5r5r7Uy-Q3k4LW1jbXRyRDA

**Comment by faix** [comment]
When adding Bloomberg logo please keep the following in mind:

The logo can be used only in the colors black, white or yellow (Pantone Yellow C) and must be placed at least .5 inches from any other logo or visual asset. When used digitally, the trademark must appear in white on a black background or black on a white background, may not be smaller than 100px in width, and should have adequate space on all sides. The trademark should never appear in a box or any other holding shape, nor may it be used in combination with any other trademark or tradename.

You can obtain the logo here: https://mlh.io/brand-guidelines
