### ISSUE TITLE
Logo full screen to white

### ISSUE THREAD

**Issue by casassg** [hackupc/old-v2-hackupc-landing#178]
Logo full screen is brown and it should be white instead

**Comment by AsLogd** [comment]
By fullscreen you mean what happens when pressing 'p'? I see the round pink logo, I don't know what you mean by brown

**Comment by wailingtam** [comment]
@AsLogd I think @casassg might be talking about the banner?

**Comment by AsLogd** [comment]
Ahh yeah I understand
