### ISSUE TITLE
Update LIVE with live updating, desktop notifications and progress bars

### ISSUE THREAD

**Issue by MarceColl** [hackupc/old-v2-hackupc-landing#22]
Current idea:
- python script for managing the json file
- small nodejs server for live updating using sockets
- desktop notifications

**Comment by casassg** [comment]
I don't think a nodejs server is needed. Simple jasvascript polling every X seconds  should be fine. We need to make sure that it's not cached by the nginx server.

**Comment by MarceColl** [comment]
Yeah, thats what Im doing, polling of the file. It seems to work fine.

**Comment by MarceColl** [comment]
It's testeable, branch events-page.

**Comment by MarceColl** [comment]
Closed: aee976f
