### ISSUE TITLE
Livestream page

### ISSUE THREAD

**Issue by MarceColl** [hackupc/old-v2-hackupc-landing#32]
Page with a link to hackupc livestream. Linked from /live

**Comment by casassg** [comment]
It may be a better idea to have it as /stream (live is our live schedule)

**Comment by MarceColl** [comment]
With linked from live I meamt that we should link to /stream from /live (top links)

**Comment by casassg** [comment]
Oh I see. Makes sense

**Comment by casassg** [comment]
Old stuff... Adding to #64 and closing this
