### ISSUE TITLE
Refactor Gulp or move away from Gulp

### ISSUE THREAD

**Issue by dasilvacontin** [hackupc/old-v2-hackupc-landing#55]

**Comment by casassg** [comment]
Gulp is currently not "compiling" correctly the project, sometimes  documents are left and you have to run gulp again. Also gulp watch is broken as well. This needs to be revisited soon

**Comment by dasilvacontin** [comment]
I propose using npm scripts directly.

**Comment by casassg** [comment]
@AsLogd is refactoring to NPM scripts

TODO:

- [ ] Refactor to npm scripts
- [ ] Add new documentation on how to run and compile the project

**Comment by casassg** [comment]
PRed in #78

**Comment by casassg** [comment]
Done in #78
