### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by dasilvacontin** [hackupc/old-v2-hackupc-landing#57]
Suggest. eg `hackupc-frontend`. Depends on how we separate client, web-server, api-server, etc.

**Comment by casassg** [comment]
maybe just landing? I mean the `hackupc` context is already visible with the organization name, isn't it? Otherwise `hackupc-landing` sounds cool too

**Comment by dasilvacontin** [comment]
`landing` feels better, in case this is only going to have the landing.

`hackupc/landing` is better than `hackupc/hackupc-landing`.

**Comment by casassg** [comment]
@dasilvacontin what about `frontend` ? I mean is similar to what other hackathons do too. And then `live` if we ever have  a live apart

**Comment by dasilvacontin** [comment]
Sure, if all the frontend is together it makes sense

**Comment by dasilvacontin** [comment]
That or fin-delantero

**Comment by casassg** [comment]
Fin-delantero plz. I will rename it when I get home
