### ISSUE TITLE
Update website palette

### ISSUE THREAD

**Issue by dasilvacontin** [hackupc/old-v2-hackupc-landing#58]
Afaik this involves updating SASS variables with new colors to give the landing a winter feel.

This updated palette is not meant to be final, but provisional. It will most likely be revisited once we start working on the logo, to keep consistency.

**Comment by casassg** [comment]
It would probably be a good option to revisit and format correctly the styles file

**Comment by dasilvacontin** [comment]
That's another issue, if you feel it's important.

**Comment by dasilvacontin** [comment]
Done in #63.
