### ISSUE TITLE
Discuss Features/info to have on /live !

### ISSUE THREAD

**Issue by dasilvacontin** [hackupc/old-v2-hackupc-landing#64]
Edit this message or post your idea.

- list of events for the whole hackathon. whole list is rendered, completed events are dimmed, crossed, wtv, and the current events get centered on the screen, by default, when you enter the site. (you can scroll as you like, might snap back to current events after some inactivity)

**Comment by dasilvacontin** [comment]
Whatever you write in here is just for the sake of discussion and brainstorming, it doesn't mean _it needs to get done_. Hold your horses.

**Comment by dasilvacontin** [comment]
From @casassg:
- Facil de canviar els events (if integrated with the backend admin interface better + API access)
- Live update de events (un usuari no ha de fer refresh quan modifiquem els events)

**Comment by dasilvacontin** [comment]
- separate repo that uses gh pages for autodeploy

**Comment by casassg** [comment]
Reasons to migrate to separate project: We can setup auto deploy as Github pages (easier to update while hackathon is happening)

**Comment by dasilvacontin** [comment]
Same project could also have auto-deploy if set up. <3

**Comment by AsLogd** [comment]
Pages:
Day of
Devpost
Maps
Hardware Lab
Travel info
Live (events)

**Comment by AsLogd** [comment]
- Desktop notifications (with options for different notifications)

**Comment by AsLogd** [comment]
- Integrate events locations with Maps

**Comment by AsLogd** [comment]
- Countdown

**Comment by casassg** [comment]
Up-> Let's move live to separate project for easier maintenance and to use live.hackupc.com

**Comment by casassg** [comment]
Also add Rules section. Also more inspiration: http://live.hackjunction.com/

**Comment by casassg** [comment]
Livestream link (if we have it)
