### ISSUE TITLE
Chrome/Android sideways scroll

### ISSUE THREAD

**Issue by MarceColl** [hackupc/old-v2-hackupc-landing#79]
Can scroll sideways, page wider than screen.

**Comment by casassg** [comment]
Pushed to production. @AsLogd @MarceColl could you test this is not happening anymore?

**Comment by ofpau** [comment]
Looks like it's well fixed, I'm seeing no horizontal scroll now.

**Comment by casassg** [comment]
Okay, then this shall be closed.
