### ISSUE TITLE
Add travel reimbursement condition in the rules of competition.

### ISSUE THREAD

**Issue by gonsp** [hackupc/old-v2-hackupc-landing#83]
Add this into the rules:

>  Participants who asked for a travel reimbursement need to post a project before the deadline in order to get the reimbursement.

Also, add it into the FAQ -> Deadline for projects submissions?

**Comment by casassg** [comment]
I would add it to rules and to DayOf page. As well as a separate a question

**Comment by gonsp** [comment]
Okay fine
