### ISSUE TITLE
Fix opening ceremony schedul in FAQ

### ISSUE THREAD

**Issue by casassg** [hackupc/old-v2-hackupc-landing#84]
- [x] Fix opening ceremony text
- [x] Add end time and date for HackUPC

**Comment by casassg** [comment]
Reported by @rashiq

**Comment by rashiq** [comment]
Oh cool didn't know this is open source!

**Comment by casassg** [comment]
Indeed it is. You can actually PR it if you want. We are focusing on the live page right now.
