### ISSUE TITLE
Add automatic deployment

### ISSUE THREAD

**Issue by casassg** [hackupc/old-v2-hackupc-landing#91]
Add automatic deployment of master branch to server. This would make it way easier to deploy schedule changes.

**Comment by casassg** [comment]
@dasilvacontin do you have time for this?

**Comment by dasilvacontin** [comment]
I'd love to, but not sure if I have the time. If I have a productice day, I might be able to fit it in this weekend.

**Comment by mauriciabad** [comment]
Done, we use Netlify to deploy automaticaly.
